version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install flask numpy pytest sklearn
  build:
    commands:
      - python -m pytest --junitxml=pytest_reports/pytest_report.xml

reports:
  pytest_reports:
    files:
      - pytest_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML